<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'CONTACT_FORM_ATTR_BODY' => 'Mitteilung',
    'CONTACT_FORM_ATTR_EMAIL' => 'E-mail',
    'CONTACT_FORM_ATTR_NAME' => 'Voller Name',
    'CONTACT_FORM_ATTR_SUBJECT' => 'Betreff',
    'CONTACT_FORM_ATTR_VERIFY_CODE' => 'Verify Code',
    'CONTACTS_FLASH_SUCCESS_MSG' => 'Mitteilung wurde erfolgreich gesendet. Danke!',
    'CONTACTS_FORM_INFO' => 'Wenn Sie Fragen oder Angebote haben, dann schreiben Sie uns doch. Danke!',
    'CONTACTS_SUBMIT_BTN' => 'Abschicken',
    'CONTACTS_TITLE' => 'Kontakte',
];
