<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'CONTACT_FORM_ATTR_BODY' => 'Mensagem',
    'CONTACT_FORM_ATTR_EMAIL' => 'E-mail',
    'CONTACT_FORM_ATTR_NAME' => 'Nome completo',
    'CONTACT_FORM_ATTR_SUBJECT' => 'Assunto',
    'CONTACT_FORM_ATTR_VERIFY_CODE' => 'Código de verificação',
    'CONTACTS_FLASH_SUCCESS_MSG' => 'Sua mensagem foi enviada. Obrigado!',
    'CONTACTS_FORM_INFO' => 'Se você tem alguma dúvida, por favor nos escreva. Obrigado!',
    'CONTACTS_SUBMIT_BTN' => 'Enviar',
    'CONTACTS_TITLE' => 'Contatos',
];
